### ISSUE TITLE
Meow "macroblock" mode

### ISSUE THREAD

**Issue by cmuratori** [cmuratori/meow_hash#20]
As of v0.2 there is a new "macroblock" mode that is experimental and supports multithreading.  It is probably not what should be standardized, but it is a starting point.  It was initially suggested by Jeff Roberts, and Fabian Giesen suggested possibly using a tree construction instead, for more distribution potential.

I'd be interested to hear thoughts on it.  I'll take a look at it again in the future for v0.3.

\- Casey

**Comment by NoHatCoder** [comment]
I wonder, what is the point of making it multithreaded? Your own benchmark shows only a modest gain from a second thread, and that is an advantage only while no other threads need a significant amount of memory access. I struggle too see a real-world case where it is an advantage.

**Comment by cmuratori** [comment]
I believe the goal here was that people wanted a way to ensure they could always extract more parallelism from it and still compute the same hash values.  At the moment, it is not likely useful, but imagine a situation where the CPUs don't get any faster at computing AES but get more memory bandwidth.  For example, suppose VAES shows up only in Xeons, and i7's eventually increase to 32bytes/cycle of memory bandwidth.  The threaded Meow hash in that hypothetical scenario would outperform the single-threaded version by 2x.

Personally, I'm not sure it's worth it, because the simplicity seems valuable and it does seem like it would take a long time to become particularly relevant, if ever.  But I do understand the fundamental argument.

\- Casey

**Comment by cmuratori** [comment]
I have retired the macroblock for now.  The consensus seems to be that it can be in a "fingerprint" mode that is added on top.

\- Casey
