### ISSUE TITLE
New benchmarking is perhaps more accurate, but difficult to stabilize

### ISSUE THREAD

**Issue by cmuratori** [cmuratori/meow_hash#34]
With the v0.3 branch, I've tried to capture a lot more of the time spent in the hashes, including any pipelined computations, as well as the full cost of branches.  I may have succeeded a little bit, but the cost is that the benchmarking is _very_ hard to stabilize now.  I would be interested in suggestions regarding how to get more consistent results, within reason (obviously there are entire systems designed for benchmark stabilization that are outside the scope of Meow hash).

\- Casey

**Comment by jan-wassenberg** [comment]
If you're on a multi-socket CPU (where TSCs are not necessarily synced), very important to pin to a single core.

Also important to add (runtime, not compiler) fences around RDTSC[P] - different sequences for starting/stopping the timer.

Finally, I'd trust robust statistics more than an outlier-prone 'best/min' measurement (possibly from turbo-boost).

Example of these techniques:
https://github.com/google/randen/blob/master/nanobenchmark.h

**Comment by cmuratori** [comment]
Correct me if I'm wrong, but the only thing we don't already do on your list is single-core pinning?  I can certainly add that.

\- Casey

**Comment by jan-wassenberg** [comment]
In meow_bench I didn't see fences before/after each RDTSC as in nanobenchmark.cc (*), nor a robust estimator (e.g. mode) of the central tendency of multiple measurements. min() is not "robust" because a single erroneous measurement is enough to corrupt the result.

* those fences are sufficient on Intel. For AMD you also need MFENCE beforehand, but they add unnecessary overhead on Intel.

**Comment by cmuratori** [comment]
Are you looking at v0.2, perhaps?

- Casey

**Comment by jan-wassenberg** [comment]
Ah, yes, I see the code is now updated (was looking at github online browser).
Median and CPUID+RDTSC, RDTSCP+CPUID look fine :) CPUID is slower but avoids the LFENCE vs MFENCE incompatibility.

**Comment by aras-p** [comment]
meow_bench crashes on Mac build on v0.3 (`7ca781dae`), due to aligned_alloc failing. The posix_memalign has a requirement that alignment must be multiple of pointer size, but the bench utility calls it with alignment of 4 for Clocks values.

**Comment by cmuratori** [comment]
Is it a sufficient fix to simply change the memory alignment to 8?

\- Casey

**Comment by aras-p** [comment]
> Is it a sufficient fix to simply change the memory alignment to 8?

Yes, then it does not crash and proceeds to actually do benchmarking work.
