### ISSUE TITLE
Should there be a C implementation?

### ISSUE THREAD

**Issue by cmuratori** [cmuratori/meow_hash#37]
C/C++ are terrible at dynamic fallbacks, since they can't JIT :(  So it sucks to have to have lots of paths.  But it's probably unavoidable.  At some point there will have to be a straight C path, and if AES instructions aren't available, it can fall back.

\- Casey

**Comment by mmozeiko** [comment]
Yes from me too. If the performance would be very horrible I would say no. But as it turns out it runs almost 1 byte per cycle. So it is not so bad. Can hash multiple gigabytes per second on PC.

I would say put the implementation behind define MEOW_USE_GENERIC_C or smth like that. And allow user to choose whether they want this hash without hw AES.

**Comment by james7132** [comment]
This is actually the main blocker for my use case over using another hash like SHA-1, where our clients need to independently verify hashes on potentially any architecture with a CPython distribution. Even if it is slow, having a portable solution is imperative in our use case.

**Comment by AndrewJDR** [comment]
I will also vote yes. I have a case in mind...

**Comment by cmuratori** [comment]
OK, I have sort-of merged in @mmozeiko's C port, which is hopefully OK by Martins?  I have not really integrated things fully yet, so it's not functional, but before I finalize v0.4 we'll have a C version.  It will be in more/meow_more.h, along with the streaming implementation.

\- Casey

**Comment by cmuratori** [comment]
As of now, the v0.4 branch has a functional C version.  It's in meow_more.h, along with the streaming version.  It requires "#define MEOW_INCLUDE_C 1" to use, because using it means that you can no longer return __m128i's directly by register, which is what we were doing before.  So _everything_ gets a tad bit slower if you require a C version, because it affects the non-C version.

\- Casey

**Comment by despair86** [comment]
Was this removed at some point? doesn't seem to be in v0.5

**Comment by NoHatCoder** [comment]
I think a new C version will probably have to wait until we are reasonably sure that we are satisfied with the algorithm.
