### ISSUE TITLE
Modern C++ rewrite

### ISSUE THREAD

**Issue by RedSpah** [cmuratori/meow_hash#4]
Hello, just wanted to showcase my rewrite of the meow hash algorithm, using modern C++ features to tidy up the codebase and get rid of the several instances of undefined behavior I found.

https://github.com/RedSpah/meow_hash_cpp

I didn't make any changes that would obviously slow the execution speed down, but note that I haven't benchmarked my version yet, so I can't know for sure.

**Comment by despair86** [comment]
>no intrinsics
wait does std C++ have generic vector FPU primitives

**Comment by Qix-** [comment]
```c
#ifdef _MSC_VER    /* Visual Studio */
#define MEOWH_FORCE_STATIC_INLINE static inline  
#else 
#ifdef __GNUC__ /* gcc, clang */
#define MEOWH_FORCE_STATIC_INLINE static inline 
#else
#define MEOWH_FORCE_STATIC_INLINE static inline
#endif
#endif
```

I don't trust code that includes this level of foolishness. That's about the point I stopped reading.
