### ISSUE TITLE
v0.5 - Should we take a nonce?

### ISSUE THREAD

**Issue by cmuratori** [cmuratori/meow_hash#48]
We are "already ingesting" a nonce, but we currently just fill it with zeroes.  There's room for 128 bits + 64 bits, so one 16-byte nonce and one 8-byte nonce.

My initial thought was perhaps the main routine doesn't bother, but the incremental code could support an additional "SetNonce(u64, u128)" or something?

\- Casey

**Comment by NoHatCoder** [comment]
That wouldn't do anything that the key/seed isn't already doing. You can call it a bit of waste to use 32 bytes of mostly 0 input to ingest the length, but putting in something else is going to cost cycles, and strengthen a part that is already a bit stronger than the rest of the ingest.

**Comment by cmuratori** [comment]
I was thinking of it more as a convenience feature, not for strength.  For example, if people are hashing blocks of a file, they could put the block number in there, rather than overwriting part of the seed or inserting it at the beginning, etc.  It's just to make it so you don't have to do "counter mode" or something else that creates more work for the programmer than just adding in a number.

AFAICT it would be free, or basically free, since it would just replace a pxor with a movdq and they are both effectively free, _especially_ on the incremental path.  I can't imagine it actually taking any more cycles, which is why it seemed like it was worth considering?  At the very least, on the incremental path where there's lots of memory reads for the state anyway, I think it would be undetectable.

\- Casey

**Comment by NoHatCoder** [comment]
The biggest problem is probably the signals such a feature would send, we do not want people to use this instead of the actual seed, it wouldn't have the same capabilities. Anyone who wants a counter mode should just ingest the counter before the data.

**Comment by cmuratori** [comment]
OK, I will remove the TODO and just say we're not taking the nonce.

\- Casey
