### ISSUE TITLE
v0.5 - Change header comments to indicate we're aiming for Level 3

### ISSUE THREAD

**Issue by cmuratori** [cmuratori/meow_hash#55]
Perhaps with the caveat that we need more crypto people looking at it before we really know how resilient it will be.

\- Casey

**Comment by cmuratori** [comment]
I've put some new text in there, but it should probably be proofed by @nohatcoder to ensure it says things the right way... I also updated the readme.md, and that should be proofread as well.

\- Casey

**Comment by NoHatCoder** [comment]
A slight catch, we need to state a seed strength, and I have no idea what strength we actually land on. I'm pretty sure that it is not 1024 bits, though I don't currently have any lower upper bound. 128 bits have been the aim throughout, but that is really just an arbitrary number. I guess we should use a wording like "aiming for 128 bits of seed strength".

**Comment by cmuratori** [comment]
Since we're "aiming for" both (128 bits of seed protection and a 128-bit hash), should we just phrase these things as "this is trying to be a Level 3 hash with 128 bits of seed protection and 128 bits of hash output, but it is still early and has not had enough analysis yet to certify those numbers"?

\- Casey

**Comment by NoHatCoder** [comment]
I don't like the word "trying", we want to be just a tad bit more assertive if the marketing is to work. Same thing goes for the analysis, we don't have to write that the dependent analysis is somewhat lacking, when the need is for independent analysis anyway. And I have never seen the word protection used like that before, it is always called strength.

How about "is designed to be a Level 3 hash with 128 bits of seed strength and 128 bits of output. Though more independent analysis is still required."

**Comment by mqudsi** [comment]
This can be closed since the decision to target level 1 was made, no?

**Comment by cmuratori** [comment]
Yes.

\- Casey
