### ISSUE TITLE
protected mode benchmark

### ISSUE THREAD

**Issue by despair86** [cmuratori/meow_hash#6]
and now, a benchmark of this algorithm, compiled for a i686 target machine in legacy protected mode
![image](https://user-images.githubusercontent.com/35446253/47260288-501f5a80-d47e-11e8-8d32-2cd6643e2ac0.png)

limiting factor is most likely the low-power mobile CPU (Pentium J3710) and the somewhat underpowered core memory. this test was done with EIST turned *OFF*

this also happens to be the only device I own that has any kind of AES instructions in the i687, all others are Core2 or earlier

**Comment by cmuratori** [comment]
Hah!  Thanks, that is a benchmark I definitely would not have been able to run myself :)
