### ISSUE TITLE
Example program does not work on Windows

### ISSUE THREAD

**Issue by niallnsec** [cmuratori/meow_hash#60]
Hi,

I think it is worth adding a note on the example program stating that it does not work properly on Windows. I ended up wasting an embarrassing amount of time thinking it was working as everything seems fine in the output, except hashed files do not match hashes generated using other tools.

It seems the issue for Windows is that the following will not reliably produce the correct size of the file:
```
fseek(File, 0, SEEK_END);
Result.Size = ftell(File);
fseek(File, 0, SEEK_SET);
```

**Comment by cmuratori** [comment]
We should probably change to using the streaming construction (included by
default now) since that would eliminate the need for reading files in their
entirety, and thus eliminate ftell compat bugs altogether...

- Casey

**Comment by NoHatCoder** [comment]
What do you mean by "other tools"? And are you sure that you are not opening the file in text mode?

Anyway, reminds me that we ought to have some official test vectors, so that it is easy to tell what implementation is wrong.

**Comment by niallnsec** [comment]
By other tools I mean I have 2 prototypes using the meow hash functions (in streaming mode and normal mode), both are in plain C using the Windows API directly to get the files size and read it. One implementation is using user mode APIs, the other is using kernel mode APIs.

When I was testing I put a couple of extra printf statements in and found that for a 24KB file I was trying to read ftell was giving me a size of 20KB whereas the Windows API call was giving me the full 24KB which agrees with the Windows properties dialog of the file.

I also tried hashing the file with the example program from a Linux VM (Debian 9) and it reported the correct file size and gave me the same hash as the other two prototypes I had put together.

After doing a bit of research it seems that ftell technically has undefined behaviour for binary streams and as mentioned text streams would have issues of their own.

**Comment by cmuratori** [comment]
That sounds highly suspicious, and it is likely you have a bug (such as
fopening the file in "r" mode instead of "rb").  While ftell can cause
compat problems on large files (if the ftell implementation is 32-bit), I
have literally never seen any problems with a 24kb file on Windows or
anywhere else.

Can you please post the code you are using?

**Comment by niallnsec** [comment]
I am using the example program exactly as it appears in the git repo and confirmed that it was getting the wrong file size by adding a single printf statement to report the size.

There is a discussion over at https://stackoverflow.com/questions/43606025/possible-to-read-a-whole-file-by-fseeking-to-seek-end-and-obtaining-the-file-s which seems to detail the problem with ftell, particularly on windows.

I am wondering if it makes a difference that I am hashing windows PE files? In particular in my tests I was looking at arp.exe on a WIndows 7 x64 box.

This is output from the example program:
![image](https://user-images.githubusercontent.com/21335031/60087298-a42cbe00-9734-11e9-9d60-9f0e7f8312df.png)

The first run is the unmodified meow_example.cpp program. The second run is my copy with the added printf for the size, and down the bottom is a printout showing the size for the file using the GetFileSizeEx API. The code for that boils down to:
```
#include <windows.h>
#include <stdio.h>

int main()
{
	HANDLE hFile = 0;
	LARGE_INTEGER fs = { 0 };

	hFile = CreateFileW(L"C:\\Windows\\System32\\arp.exe",
		GENERIC_READ,
		0,
		NULL,
		OPEN_EXISTING,
		FILE_ATTRIBUTE_NORMAL,
		NULL);
	
	if (hFile == INVALID_HANDLE_VALUE)
	{
		printf("Invalid handle  value");
		return;
	}
	if (GetFileSizeEx(hFile, &fs)) printf("Size: %d\n",fs.LowPart);
	else printf("Failed to get size\n");
}
```
(Note: the results were the same for both meow_example.exe and meow_example_c.exe)

I also included the Windows property file dialog in the screenshot so you can see the size reported by the OS.

**Comment by niallnsec** [comment]
Okay I might have found something interesting here. Since on Windows fseek to the end of a file followed by ftell is technically undefined, although it usually works due to implementation details, it can produce different results depending on the scenario.

I tried copying arp.exe to a test folder as I recall that Windows uses some NTFS features to reduce the size of the Windows directory. I think that is confusing fseek and ftell.
Here is the output from hashing the same file both in the System32 directory and in a test directory:
![image](https://user-images.githubusercontent.com/21335031/60087861-b0fde180-9735-11e9-99ca-b5d89e265ef4.png)

It seems that a difference in the NTFS structure is whats causing the different behaviour, I expect it is only accounted for when using the Windows APIs.

**Comment by mmozeiko** [comment]
I am 100% sure ftell is not a bug here. So many applications uses ftell like this to get size of file. If this would not work then you would see crashes left and right.

Did you by any chance compile one executable as 32-bit, and other as 64-bit? Because `C:\Windows\system32\arp.exe` file will be different for 32-bit or 64-bit process (when using 64-bit Windows). 32-bit process will actually read `C:\Windows\SysWOW64\arp.exe` file.

**Comment by niallnsec** [comment]
Ahhh, nice spot. I did not expect Wow64 redirection to occur when reading a data file. You are quite right, the SysWOW64 version of ARP.EXE has a size of 20992.

Thanks and apologies for my mistake.

**Comment by cmuratori** [comment]
Although it is probably appropriate to close this issue because there was no actual bug of the kind reported, I am going to open a separate issue for replacing ftell because there _are_ cases where it would be misleading, such as 32-bit builds with 64-bit file lengths, etc.  Since the streaming construction ships in the main header by default, there's no reason we can't just do a looped fread into a fixed-size buffer.

\- Casey
