### ISSUE TITLE
dotnet (c#) bindings

### ISSUE THREAD

**Issue by dan-2019** [cmuratori/meow_hash#64]
I'm interested in using meow hash in c#.
Does a binding exist for dot net?

**Comment by cmuratori** [comment]
We don't really follow ports, so I couldn't say.  On this repository, we only keep the native C implementation.  There have been ports to many languages though, so you may be able to find a Meow 0.5 in C#.

When I finally get the time to finalize this distribution, we can certainly put a "link to ports" section on the readme, if people want to submit them.

\- Casey
