### ISSUE TITLE
How deterministic is Meow hash?

### ISSUE THREAD

**Issue by pckhoi** [cmuratori/meow_hash#65]
I have tests that randomly fail because I also test the output hash string. I have witness the output fluctuate between at least 2 variants given the same input.

**Comment by NoHatCoder** [comment]
It should be deterministic. Could you provide some sample code?

**Comment by pckhoi** [comment]
Please keep this open. I'm posting sample code as soon as I can produce a minimal working sample.

**Comment by cmuratori** [comment]
Meow Hash is deterministic.  The SMHasher sanity tests would fail immediately (as would meow_test.cpp) if it was not.

Unless the sample code is forthcoming, I would prefer to close the issue, and you can open a fresh issue with the repro case if you do find one.

\- Casey

**Comment by pckhoi** [comment]
Sorry, my mistake. I fed a map into the hash function and map has no order so the result was random. Replacing the map with slice seems to solve it.
