### ISSUE TITLE
.NET Core 3.1 port.

### ISSUE THREAD

**Issue by tvandijck** [cmuratori/meow_hash#75]
Not really an issue, but in this gist is a port of the algorithm to C# using the new .NET Core intrinsics.
Feel free to include this in repro or I can make a separate repo for it and post/maintain it on nuget.
whatever you feel is appropriate.

https://gist.github.com/tvandijck/a9160c49a36ba652e0cab647cbc1a1b8

**Comment by cmuratori** [comment]
I don't want to actually manage other languages in this repository, but if would be nice if people had an easy way to look up ports.  Perhaps you can make a separate repo for it, and then I can put a link in the readme here so people can hop to other language repos based on which language they need?

\- Casey

**Comment by tvandijck** [comment]
https://github.com/tvandijck/meow_hash.NET

I'll add ci & nuget etc later... for now this is the initial port of just the algorithm at current head.
It produces the same hashes, but I'm not sure what the performance metrics are.
